#if !defined(_RADIOLIB_USER_BUILD_OPTIONS_H)
#define _RADIOLIB_USER_BUILD_OPTIONS_H

/* nRF54L15 Zephyr port — exclude all modules except LR2021 */
#define RADIOLIB_EXCLUDE_CC1101     1
#define RADIOLIB_EXCLUDE_LLCC68     1
#define RADIOLIB_EXCLUDE_NRF24      1
#define RADIOLIB_EXCLUDE_RF69       1
#define RADIOLIB_EXCLUDE_RFM2x      1
#define RADIOLIB_EXCLUDE_SI443X     1
#define RADIOLIB_EXCLUDE_SX123X     1
#define RADIOLIB_EXCLUDE_SX126X     1
#define RADIOLIB_EXCLUDE_SX127X     1
#define RADIOLIB_EXCLUDE_SX128X     1
#define RADIOLIB_EXCLUDE_LR11X0     1
#define RADIOLIB_EXCLUDE_STM32WLX   1
#define RADIOLIB_EXCLUDE_PAGER      1
#define RADIOLIB_EXCLUDE_SSTV       1
#define RADIOLIB_EXCLUDE_HELLSCHREIBER 1
#define RADIOLIB_EXCLUDE_MORSE      1
#define RADIOLIB_EXCLUDE_RTTY       1
#define RADIOLIB_EXCLUDE_AFSK       1
#define RADIOLIB_EXCLUDE_AX25       1
#define RADIOLIB_EXCLUDE_BELL       1
#define RADIOLIB_EXCLUDE_FSK4       1
#define RADIOLIB_EXCLUDE_APRS       1
#define RADIOLIB_EXCLUDE_LORAWAN    1
#define RADIOLIB_EXCLUDE_DIRECT_RECEIVE 1

#define RADIOLIB_STATIC_ONLY        1
#define RADIOLIB_DEBUG_BASIC        (0)
#define RADIOLIB_DEBUG_SPI          (0)

#endif
